from django.urls import path
from . import views
urlpatterns = [
   path('', views.home, name='home'),
   path('shop/', views.shop, name='shop'),
   path('category/<slug:slug>/', views.shop_by_category, name='shop_by_category'),
   path('product/<slug:slug>/', views.product_detail, name='product_detail'),
   path('about/', views.about, name='about'),
   path('contact/', views.contact, name='contact'),
   path('faqs/', views.faqs, name='faqs'),
   path('return-policy/', views.return_policy, name='return_policy'),
   path('track-order/', views.order_tracking, name='order_tracking'),
   path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
   path('payment-info/', views.payment_info, name='payment_info'),
   path('shipping-info/', views.shipping_info, name='shipping_info'),
   path('newsletter-signup/', views.newsletter_signup, name='newsletter_signup'),

   path('wishlist/items/', views.wishlist_items, name='wishlist_items'),
   path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
   path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
   path('wishlist/add-redirect/<int:product_id>/', views.add_to_wishlist_redirect, name='add_to_wishlist_redirect'),  
   path('wishlist/count/', views.wishlist_count, name='wishlist_count'),

   path('add-to-cart/<slug:slug>/<str:size>/', views.add_to_cart, name='add_to_cart_with_size'),
   path('cart/sidebar/', views.cart_sidebar, name='cart-sidebar'),
   path('cart/sidebar/', views.cart_sidebar_view, name='cart_sidebar'),
   path('add-to-cart/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
   path('decrease-quantity/<slug:product_slug>/', views.decrease_quantity, name='decrease_quantity'),
   path('decrease-quantity/<slug:product_slug>/<str:size>/', views.decrease_quantity, name='decrease_quantity_with_size'),
   path('remove-from-cart/<slug:product_slug>/', views.remove_from_cart, name='remove_from_cart'),
   path('remove-from-cart/<slug:product_slug>/<str:size>/', views.remove_from_cart, name='remove_from_cart_with_size'),


   path('category/<slug:slug>/', views.shop_by_category, name='shop_by_category'),
   path('category/', views.shop_all, name='shop_all'),
   path('category/<slug:category_slug>/', views.shop_by_category, name='shop_by_category'),
   path('category/<slug:category_slug>/<slug:subcategory_slug>/', views.shop_by_subcategory, name='shop_by_subcategory'),

   path('address/', views.address_view, name='address'),
   path('address/update/', views.update_address, name='update-address'),
   path('address/add/', views.add_address, name='add-address'),
   path('checkout/', views.checkout, name='checkout'),
   path('place-order/', views.place_order, name='place_order'),
   path('orders/', views.user_orders, name='user_orders'),
   path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
   path('my-orders/', views.my_orders, name='my_orders'),
   path('get-dynamic-price/', views.get_dynamic_price, name='get_dynamic_price'),
   path('ai-dashboard/', views.ai_dashboard, name='ai_dashboard'),
   path('dynamic-pricing/', views.dynamic_pricing, name='dynamic_pricing'),
   path('dashboard/products_dashboard/', views.products_dashboard, name='products_dashboard'),
   path('dashboard/orders_dashboard/', views.orders_dashboard, name='orders_dashboard'),
   path('dashboard/categories_dashboard/', views.categories_dashboard, name='categories_dashboard'),
   path('lock-discount/<int:product_id>/', views.lock_discount, name='lock_discount'),
   path( 'unlock-discount/<int:product_id>/', views.unlock_discount, name='unlock_discount'),
   path( 'toggle-discount-lock/<int:product_id>/', views.toggle_discount_lock, name='toggle_discount_lock'),
   ]