# Generated by Django 5.2.1 on 2025-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0003_remove_category_parent_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
