# Generated by Django 5.2.1 on 2025-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric_details',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
