# Generated by Django 5.2.1 on 2025-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0007_product_fabric_details_product_is_recent_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=100),
        ),
    ]
