# Generated by Django 5.2.1 on 2025-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
