# Generated by Django 5.2.1 on 2025-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0014_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Unknown address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='Punjab', max_length=100),
            preserve_default=False,
        ),
    ]
