# Generated by Django 5.2.1 on 2025-06-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0017_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
