# Generated by Django 5.2.1 on 2025-06-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0018_remove_order_product_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
