# Generated by Django 5.2.1 on 2025-06-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0020_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
