# Generated by Django 5.2.1 on 2025-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0022_cartitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_unstitched',
            field=models.BooleanField(default=False),
        ),
    ]
