# Generated by Django 5.2.1 on 2026-05-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0032_alter_cartitem_unique_together_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='dynamic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(default='Night', max_length=50),
        ),
    ]
