# Generated by Django 5.2.1 on 2026-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0033_product_average_rating_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_locked',
            field=models.BooleanField(default=False),
        ),
    ]
